version: '3'

services:
   db:
     image: mysql:latest
     volumes:
       - /var/lib/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: senhaforte
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: senhaforte2
     networks:
       - wp-net  

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     volumes:
       - /var/www/html:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: senhaforte2
       WORDPRESS_DB_NAME: wordpress
     ports:
       - "80"
     networks:
       - wp-net 
     deploy:
      mode: replicated
      replicas: 3

   nginx:
     depends_on:
       - wordpress
     image: jmarquescl/nginx-alpine:wp-OneCont
     restart: always
     ports:
       - "80:80"
     networks:
       - wp-net
     deploy:
      mode: global

networks:
    wp-net:    
     
