version: '3'

services:
   db:
     image: mysql:latest
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: senhaforte
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: outrasenhaforte
     networks: 
       - "projeto"
     container_name: banco-wp

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     volumes:
       - ./wordpress:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: outrasenhaforte
       WORDPRESS_DB_NAME: wordpress
     ports:
       - "80"
     networks: 
       - "projeto"
     container_name: wordpress

   wordpress2:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     volumes:
       - ./wordpress:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: outrasenhaforte
       WORDPRESS_DB_NAME: wordpress
     ports:
       - "80"
     networks: 
       - "projeto"
     container_name: wordpress2


   wordpress3:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     volumes:
       - ./wordpress:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: outrasenhaforte
       WORDPRESS_DB_NAME: wordpress
     ports:
       - "80"
     networks: 
       - "projeto"
     container_name: wordpress3

   nginx:
     depends_on:
       - wordpress
       - wordpress2
       - wordpress3
     restart: always
     build:
       context: .
       dockerfile: Dockerfile-nginx
     ports:
       - "80:80"
     networks: 
       - "projeto"
     container_name: nginx-wp

networks:
  projeto:
    driver: bridge